export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM';

export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM';

export const BASKET_CLEAR = 'BASKET_CLEAR';

export const BASKET_REMOVE_ALL = 'BASKET_REMOVE_ALL';
